# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:
  - Name: Orderer
    Domain: supplychain.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Manufacturer
    Domain: manufacturer.supplychain.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Logistics
    Domain: logistics.supplychain.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Retailer
    Domain: retailer.supplychain.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

